// All included (excepted deprecated upcoming)
// see bourbon/app/Assets/stylesheets/_bourbon.scss for possible scss to import

module.exports = {

	'settings/prefixer': true,
	'settings/px-to-em': true,
	'settings/asset-pipeline': true,

	'functions/assign-inputs': true,
	'functions/contains': true,
	'functions/contains-falsy': true,
	'functions/is-length': true,
	'functions/is-light': true,
	'functions/is-number': true,
	'functions/is-size': true,
	'functions/px-to-em': true,
	'functions/px-to-rem': true,
	'functions/shade': true,
	'functions/strip-units': true,
	'functions/tint': true,
	'functions/transition-property-name': true,
	'functions/unpack': true,
	'functions/modular-scale': true,

	'helpers/convert-units': true,
	'helpers/directional-values': true,
	'helpers/font-source-declaration': true,
	'helpers/gradient-positions-parser': true,
	'helpers/linear-angle-parser': true,
	'helpers/linear-gradient-parser': true,
	'helpers/linear-positions-parser': true,
	'helpers/linear-side-corner-parser': true,
	'helpers/radial-arg-parser': true,
	'helpers/radial-positions-parser': true,
	'helpers/radial-gradient-parser': true,
	'helpers/render-gradients': true,
	'helpers/shape-size-stripper': true,
	'helpers/str-to-num': true,

	'css3/animation': true,
	'css3/appearance': true,
	'css3/backface-visibility': true,
	'css3/background': true,
	'css3/background-image': true,
	'css3/border-image': true,
	'css3/calc': true,
	'css3/columns': true,
	'css3/filter': true,
	'css3/flex-box': true,
	'css3/font-face': true,
	'css3/font-feature-settings': true,
	'css3/hidpi-media-query': true,
	'css3/hyphens': true,
	'css3/image-rendering': true,
	'css3/keyframes': true,
	'css3/linear-gradient': true,
	'css3/perspective': true,
	'css3/placeholder': true,
	'css3/radial-gradient': true,
	'css3/selection': true,
	'css3/text-decoration': true,
	'css3/transform': true,
	'css3/transition': true,
	'css3/user-select': true,

	'addons/border-color': true,
	'addons/border-radius': true,
	'addons/border-style': true,
	'addons/border-width': true,
	'addons/buttons': true,
	'addons/clearfix': true,
	'addons/ellipsis': true,
	'addons/font-stacks': true,
	'addons/hide-text': true,
	'addons/margin': true,
	'addons/padding': true,
	'addons/position': true,
	'addons/prefixer': true,
	'addons/retina-image': true,
	'addons/size': true,
	'addons/text-inputs': true,
	'addons/timing-functions': true,
	'addons/triangle': true,
	'addons/word-wrap': true,

	'bourbon-deprecated-upcoming': false
};
